/**
         * Property-based tests using fast-check
         * These tests verify correctness properties across randomized inputs
         */
        const PropertyTests = {
            /**
             * Property 12: Execution State Completeness
             * Feature: python-execution-visualizer, Property 12
             * Validates: Requirements 7.9
             * 
             * For any execution step generated by the execution engine, the corresponding 
             * ExecutionState should contain all required fields: stepNumber, lineNumber, 
             * pipelineStage, instructionPointer, bytecode, callStack, heap, gilStatus, and explanation.
             */
            testExecutionStateCompleteness: function() {
                const result = fc.assert(
                    fc.property(
                        // Generate arbitrary ExecutionState-like objects
                        fc.record({
                            stepNumber: fc.nat(),
                            lineNumber: fc.integer({ min: 1, max: 1000 }),
                            pipelineStage: fc.constantFrom('source', 'tokenizer', 'parser', 'compiler', 'bytecode', 'pvm'),
                            instructionPointer: fc.nat(),
                            bytecode: fc.array(fc.record({
                                offset: fc.nat(),
                                opname: fc.string(),
                                arg: fc.oneof(fc.nat(), fc.constant(null)),
                                argval: fc.anything(),
                                lineno: fc.integer({ min: 1, max: 1000 })
                            })),
                            callStack: fc.array(fc.record({
                                frameId: fc.string(),
                                functionName: fc.string(),
                                localVariables: fc.dictionary(fc.string(), fc.anything()),
                                returnAddress: fc.nat(),
                                lineNumber: fc.integer({ min: 1, max: 1000 })
                            })),
                            heap: fc.array(fc.record({
                                objectId: fc.string(),
                                type: fc.constantFrom('int', 'str', 'list', 'dict', 'function'),
                                value: fc.anything(),
                                refCount: fc.nat(),
                                references: fc.array(fc.string())
                            })),
                            gilStatus: fc.record({
                                state: fc.constantFrom('ACQUIRED', 'RELEASED'),
                                threadId: fc.integer(),
                                explanation: fc.string()
                            }),
                            explanation: fc.string()
                        }),
                        (stateData) => {
                            // Create ExecutionState from generated data
                            const state = new ExecutionState(stateData);
                            
                            // Verify all required fields are present and not undefined
                            const hasAllFields = 
                                state.stepNumber !== undefined &&
                                state.lineNumber !== undefined &&
                                state.pipelineStage !== undefined &&
                                state.instructionPointer !== undefined &&
                                state.bytecode !== undefined &&
                                state.callStack !== undefined &&
                                state.heap !== undefined &&
                                state.gilStatus !== undefined &&
                                state.explanation !== undefined;
                            
                            return hasAllFields;
                        }
                    ),
                    { numRuns: 100, verbose: true }
                );
                
                return result;
            },
            
            /**
             * Property 13: Step Forward Advances State
             * Feature: python-execution-visualizer, Property 13
             * Validates: Requirements 8.6
             * 
             * For any execution state where the current index is not at the end of the states array,
             * calling stepForward should increment the current index by exactly one.
             */
            testStepForwardAdvancesState: function() {
                const result = fc.assert(
                    fc.property(
                        // Generate array of states and a valid starting index
                        fc.array(fc.record({
                            stepNumber: fc.nat(),
                            lineNumber: fc.integer({ min: 1, max: 100 }),
                            pipelineStage: fc.constantFrom('source', 'tokenizer', 'parser', 'compiler', 'bytecode', 'pvm'),
                            instructionPointer: fc.nat(),
                            bytecode: fc.array(fc.record({
                                offset: fc.nat(),
                                opname: fc.string(),
                                arg: fc.oneof(fc.nat(), fc.constant(null)),
                                argval: fc.anything(),
                                lineno: fc.integer({ min: 1, max: 100 })
                            })),
                            callStack: fc.array(fc.record({
                                frameId: fc.string(),
                                functionName: fc.string(),
                                localVariables: fc.dictionary(fc.string(), fc.anything()),
                                returnAddress: fc.nat(),
                                lineNumber: fc.integer({ min: 1, max: 100 })
                            })),
                            heap: fc.array(fc.record({
                                objectId: fc.string(),
                                type: fc.constantFrom('int', 'str', 'list', 'dict', 'function'),
                                value: fc.anything(),
                                refCount: fc.nat(),
                                references: fc.array(fc.string())
                            })),
                            gilStatus: fc.record({
                                state: fc.constantFrom('ACQUIRED', 'RELEASED'),
                                threadId: fc.integer(),
                                explanation: fc.string()
                            }),
                            explanation: fc.string()
                        }), { minLength: 2 }), // At least 2 states to test stepping
                        (statesData) => {
                            const store = new StateStore();
                            const states = statesData.map(data => new ExecutionState(data));
                            store.setStates(states);
                            
                            // Test stepping forward from each valid position
                            for (let i = 0; i < states.length - 1; i++) {
                                store.currentIndex = i;
                                const initialIndex = store.currentIndex;
                                const result = store.stepForward();
                                
                                // Should return true and increment by exactly 1
                                if (!result || store.currentIndex !== initialIndex + 1) {
                                    return false;
                                }
                            }
                            
                            return true;
                        }
                    ),
                    { numRuns: 100, verbose: true }
                );
                
                return result;
            },
            
            /**
             * Property 14: Step Back Reverses State
             * Feature: python-execution-visualizer, Property 14
             * Validates: Requirements 8.7
             * 
             * For any execution state where the current index is not at the beginning of the states array,
             * calling stepBack should decrement the current index by exactly one.
             */
            testStepBackReversesState: function() {
                const result = fc.assert(
                    fc.property(
                        // Generate array of states
                        fc.array(fc.record({
                            stepNumber: fc.nat(),
                            lineNumber: fc.integer({ min: 1, max: 100 }),
                            pipelineStage: fc.constantFrom('source', 'tokenizer', 'parser', 'compiler', 'bytecode', 'pvm'),
                            instructionPointer: fc.nat(),
                            bytecode: fc.array(fc.record({
                                offset: fc.nat(),
                                opname: fc.string(),
                                arg: fc.oneof(fc.nat(), fc.constant(null)),
                                argval: fc.anything(),
                                lineno: fc.integer({ min: 1, max: 100 })
                            })),
                            callStack: fc.array(fc.record({
                                frameId: fc.string(),
                                functionName: fc.string(),
                                localVariables: fc.dictionary(fc.string(), fc.anything()),
                                returnAddress: fc.nat(),
                                lineNumber: fc.integer({ min: 1, max: 100 })
                            })),
                            heap: fc.array(fc.record({
                                objectId: fc.string(),
                                type: fc.constantFrom('int', 'str', 'list', 'dict', 'function'),
                                value: fc.anything(),
                                refCount: fc.nat(),
                                references: fc.array(fc.string())
                            })),
                            gilStatus: fc.record({
                                state: fc.constantFrom('ACQUIRED', 'RELEASED'),
                                threadId: fc.integer(),
                                explanation: fc.string()
                            }),
                            explanation: fc.string()
                        }), { minLength: 2 }), // At least 2 states to test stepping back
                        (statesData) => {
                            const store = new StateStore();
                            const states = statesData.map(data => new ExecutionState(data));
                            store.setStates(states);
                            
                            // Test stepping back from each valid position
                            for (let i = 1; i < states.length; i++) {
                                store.currentIndex = i;
                                const initialIndex = store.currentIndex;
                                const result = store.stepBack();
                                
                                // Should return true and decrement by exactly 1
                                if (!result || store.currentIndex !== initialIndex - 1) {
                                    return false;
                                }
                            }
                            
                            return true;
                        }
                    ),
                    { numRuns: 100, verbose: true }
                );
                
                return result;
            },
            
            /**
             * Property 15: Reset Returns to Initial State
             * Feature: python-execution-visualizer, Property 15
             * Validates: Requirements 8.9
             * 
             * For any execution state at any index, calling reset should set the current index to zero.
             */
            testResetReturnsToInitialState: function() {
                const result = fc.assert(
                    fc.property(
                        // Generate array of states and a random starting index
                        fc.array(fc.record({
                            stepNumber: fc.nat(),
                            lineNumber: fc.integer({ min: 1, max: 100 }),
                            pipelineStage: fc.constantFrom('source', 'tokenizer', 'parser', 'compiler', 'bytecode', 'pvm'),
                            instructionPointer: fc.nat(),
                            bytecode: fc.array(fc.record({
                                offset: fc.nat(),
                                opname: fc.string(),
                                arg: fc.oneof(fc.nat(), fc.constant(null)),
                                argval: fc.anything(),
                                lineno: fc.integer({ min: 1, max: 100 })
                            })),
                            callStack: fc.array(fc.record({
                                frameId: fc.string(),
                                functionName: fc.string(),
                                localVariables: fc.dictionary(fc.string(), fc.anything()),
                                returnAddress: fc.nat(),
                                lineNumber: fc.integer({ min: 1, max: 100 })
                            })),
                            heap: fc.array(fc.record({
                                objectId: fc.string(),
                                type: fc.constantFrom('int', 'str', 'list', 'dict', 'function'),
                                value: fc.anything(),
                                refCount: fc.nat(),
                                references: fc.array(fc.string())
                            })),
                            gilStatus: fc.record({
                                state: fc.constantFrom('ACQUIRED', 'RELEASED'),
                                threadId: fc.integer(),
                                explanation: fc.string()
                            }),
                            explanation: fc.string()
                        }), { minLength: 1 }),
                        fc.nat(),
                        (statesData, randomIndex) => {
                            const store = new StateStore();
                            const states = statesData.map(data => new ExecutionState(data));
                            store.setStates(states);
                            
                            // Set to a random valid index
                            if (states.length > 0) {
                                store.currentIndex = randomIndex % states.length;
                            }
                            
                            // Reset should always return to index 0
                            store.reset();
                            
                            return store.currentIndex === 0;
                        }
                    ),
                    { numRuns: 100, verbose: true }
                );
                
                return result;
            },
            
            /**
             * Run all property tests
             * @returns {Object} Test results with pass/fail status for each test
             */
            runAll: function() {
                console.log('Running property-based tests...');
                const results = {};

                // Skip all property tests if fast-check is not available
                if (typeof fc === 'undefined') {
                    console.warn('fast-check (fc) not available — skipping property-based tests');
                    return results;
                }
                
                try {
                    console.log('Testing Property 12: Execution State Completeness...');
                    this.testExecutionStateCompleteness();
                    results.executionStateCompleteness = { passed: true, error: null };
                    console.log('✓ Property 12 passed');
                } catch (error) {
                    results.executionStateCompleteness = { passed: false, error: error.message };
                    console.error('✗ Property 12 failed:', error.message);
                }
                
                try {
                    console.log('Testing Property 13: Step Forward Advances State...');
                    this.testStepForwardAdvancesState();
                    results.stepForwardAdvancesState = { passed: true, error: null };
                    console.log('✓ Property 13 passed');
                } catch (error) {
                    results.stepForwardAdvancesState = { passed: false, error: error.message };
                    console.error('✗ Property 13 failed:', error.message);
                }
                
                try {
                    console.log('Testing Property 14: Step Back Reverses State...');
                    this.testStepBackReversesState();
                    results.stepBackReversesState = { passed: true, error: null };
                    console.log('✓ Property 14 passed');
                } catch (error) {
                    results.stepBackReversesState = { passed: false, error: error.message };
                    console.error('✗ Property 14 failed:', error.message);
                }
                
                try {
                    console.log('Testing Property 15: Reset Returns to Initial State...');
                    this.testResetReturnsToInitialState();
                    results.resetReturnsToInitialState = { passed: true, error: null };
                    console.log('✓ Property 15 passed');
                } catch (error) {
                    results.resetReturnsToInitialState = { passed: false, error: error.message };
                    console.error('✗ Property 15 failed:', error.message);
                }
                
                return results;
            }
        };